// All languages made availables on the 10fastfingers website
export const availableLang = {
	albanian: { value: 'Shqip', flagId: 30 },
	arabic: { value: 'العربية', flagId: 27 },
	armenian: { value: 'հայերեն', flagId: 41 },
	azerbaijani: { value: 'Azərbaycanca', flagId: 43 },
	bengali: { value: 'বাংলা', flagId: 56 },
	bulgarian: { value: 'Български', flagId: 28 },
	catalan: { value: 'Català', flagId: 23 },
	'chinese simplified': { value: '简体中文', flagId: 16 },
	'chinese traditional': { value: '繁體中文', flagId: 15 },
	croatian: { value: 'Hrvatski', flagId: 25 },
	czech: { value: 'Česky', flagId: 33 },
	danish: { value: 'Dansk', flagId: 17 },
	dutch: { value: 'Nederlands', flagId: 18 },
	english: { value: 'English', flagId: 1 },
	esperanto: { value: 'Esperanto', flagId: 52 },
	estonian: { value: 'Eesti', flagId: 34 },
	filipino: { value: 'filipino', flagId: 24 },
	finnish: { value: 'Suomi', flagId: 21 },
	french: { value: 'Français', flagId: 3 },
	galician: { value: 'Galego', flagId: 38 },
	georgian: { value: 'ქართული ენა', flagId: 40 },
	german: { value: 'Deutsch', flagId: 2 },
	greek: { value: 'Ελληνικά', flagId: 32 },
	hebrew: { value: 'עברית', flagId: 36 },
	hindi: { value: 'हिन्दी', flagId: 44 },
	hungarian: { value: 'Magyar', flagId: 14 },
	icelandic: { value: 'íslenska', flagId: 48 },
	indonesian: { value: 'Bahasa Indonesia', flagId: 6 },
	italian: { value: 'Italiano', flagId: 20 },
	japanese: { value: '日本語', flagId: 29 },
	korean: { value: '한국어', flagId: 31 },
	kurdish: { value: 'کوردی', flagId: 42 },
	latvian: { value: 'latviešu valoda', flagId: 35 },
	lithuanian: { value: 'Lietuvių', flagId: 39 },
	macedonian: { value: 'Makedonski', flagId: 54 },
	malagasy: { value: 'Malagasy', flagId: 55 },
	malaysian: { value: 'Bahasa Melayu', flagId: 11 },
	norwegian: { value: 'Norsk', flagId: 12 },
	pashto: { value: 'پښتو', flagId: 51 },
	persian: { value: 'فارسی', flagId: 13 },
	polish: { value: 'Polski', flagId: 9 },
	portuguese: { value: 'Português', flagId: 4 },
	romanian: { value: 'Română', flagId: 10 },
	russian: { value: 'Русский', flagId: 26 },
	serbian: { value: 'Српски / Srpski', flagId: 22 },
	slovak: { value: 'Slovenčina', flagId: 45 },
	slovenian: { value: 'Slovenščina', flagId: 46 },
	spanish: { value: 'Español', flagId: 5 },
	swedish: { value: 'Svenska', flagId: 19 },
	thai: { value: 'ภาษาไทย', flagId: 50 },
	turkish: { value: 'Türkçe', flagId: 7 },
	ukrainian: { value: 'українська', flagId: 53 },
	urdu: { value: 'اُردُو', flagId: 37 },
	vietnamese: { value: 'Tiếng Việt', flagId: 8 }
};
