name: CI

on:
  push:
  pull_request:

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: node
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: |
          yarn
          yarn format:check
          yarn lint
          yarn test
          yarn build