name: CI

on:
  push:
    branches: ["v2.x"]
  pull_request:
    branches: ["v2.x"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: node
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run test
